# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170508_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='order_user',
            name='time',
        ),
    ]
