# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170510_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_menu',
            old_name='type_text',
            new_name='types',
        ),
    ]
